#!/usr/bin/env python
from run_analysis import *
import optparse


def main():
    parser = optparse.OptionParser()
    (options, args) = parser.parse_args()

    if len(args) <= 2 or len(args)%2 != 1:
        print "Usage: %s ros_distro  stack_name "%sys.argv[0]
        print " - with ros_distro the name of the ros distribution (e.g. 'electric' or 'fuerte' or 'groovy')"
        print " - with stack_name the name of the stack you want to analyze"
        print " - build_system 'dry' or 'wet'."
        raise BuildException("Wrong arguments for code_quality_stack script")

    ros_distro = args[0]
    stack_name = args[1]
    build_system = args[2]
    workspace = os.environ['WORKSPACE']

    print "Running code_quality_stack on distro %s and stack %s"%(ros_distro,stack_name)
    run_analysis(ros_distro, stack_name, workspace, build_system, test_depends_on=True)


if __name__ == '__main__':
    # global try
    try:
        main()
        print "code_quality_stack script finished cleanly"

    # global catch
    except BuildException as ex:
        print ex.msg

    except Exception as ex:
        print "code_quality_stack script failed. Check out the console output above for details."
        raise ex
