#!/bin/bash

#Script to document distro independent ROS tools that use sphinx for
#documentation. The requirement for a repo is that it expose a "make html"
#target from a makefile in the doc directory that places its output in
#doc/_build/html

REPOS="https://github.com/vcstools/vcstools.git
https://github.com/vcstools/rosinstall.git
https://github.com/ros/rospkg.git
https://github.com/ros/rosdep.git
https://github.com/ros-infrastructure/rosdistro.git
https://github.com/ros-infrastructure/jenkins_tools.git"

#Make sure to set up ros sources for apt
echo "deb http://packages.ros.org/ros/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list
wget http://packages.ros.org/ros.key -O $WORKSPACE/ros.key
apt-key add $WORKSPACE/ros.key
apt-get update
apt-get install python-catkin-sphinx rsync --yes

DOC_DIR="$WORKSPACE/documentation_gen"

rm -rf $DOC_DIR
mkdir $DOC_DIR
cd $DOC_DIR

for r in $REPOS
do
  git clone $r
done

DIRS="`find . -maxdepth 1 -mindepth 1 -type d -exec basename '{}' \;`"
export PYTHONPATH=""

for d in $DIRS
do
  export PYTHONPATH=$DOC_DIR/$d/src:$PYTHONPATH
done

for d in $DIRS
do
  echo "DOCUMENTING $d"
  cd $d/doc
  #make upload
  make html
  chmod -R g+w _build/html/
  rsync -e "ssh -o StrictHostKeyChecking=no" -qr _build/html rosbuild@wgs32:/var/www/www.ros.org/html/doc_ind/api/$d
  cd ../../
  echo "--------------------------------"
done

cd ../
rm -rf $DOC_DIR
