#!/bin/bash

#Script to document distro independent ROS tools that use sphinx for
#documentation. The requirement for a repo is that it expose a "make html"
#target from a makefile in the doc directory that places its output in
#doc/_build/html

REPOS="https://github.com/vcstools/vcstools.git
https://github.com/vcstools/rosinstall.git
https://github.com/ros/rospkg.git
https://github.com/ros/rosdep.git
https://github.com/vcstools/wstool.git
https://github.com/ros-infrastructure/rosdistro.git
https://github.com/ros-infrastructure/jenkins_tools.git"

sudo apt-get install python-catkin-sphinx --yes

DOC_DIR="$WORKSPACE/documentation_gen"

rm -rf $DOC_DIR
mkdir $DOC_DIR
cd $DOC_DIR

for r in $REPOS
do
  git clone $r
done

DIRS="`find . -maxdepth 1 -mindepth 1 -type d -exec basename '{}' \;`"
for d in $DIRS
do
  echo "DOCUMENTING $d"
  cd $d/doc
  #make upload
  make html
  chmod -R g+w _build/html/
  scp -pr _build/html/ wgs32.willowgarage.com:/var/www/www.ros.org/html/doc_ind/api/$d
  cd ../../
  echo "--------------------------------"
done

cd ../
rm -rf $DOC_DIR
